version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: animaliadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - backend_network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/animaliadb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9000:9000"
    networks:
      - backend_network
      - frontend_network

  frontend:
    build:
      context: ./frontend/Animalia
      dockerfile: Dockerfile
    container_name: frontend_container
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - frontend_network


networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge


volumes:
  mysql_data:
